# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_b64_wrappers", use_symbols = TRUE, package_name = "b64")

#' @docType package
#' @usage NULL
#' @useDynLib b64, .registration = TRUE
NULL

#' Encode to base64
#' 
#' @param input A string, raw vector, or file path.
#' @export
#' @name encode
encode_string <- function(input) .Call(wrap__encode_string, input)

#' @export
#' @name encode
encode_raw <- function(input) .Call(wrap__encode_raw, input)

#' @export
#' @name encode
encode_file <- function(path) .Call(wrap__encode_file, path)

#' Decode from base64
#' 
#' @param input A string or raw vector.
#' @export
#' @name decode
decode_string <- function(input) .Call(wrap__decode_string, input)

#' @export
#' @name decode
decode_raw <- function(input) .Call(wrap__decode_raw, input)

chunk_encoding <- function(encoded, size) .Call(wrap__chunk_encoding, encoded, size)

collapse_chunks <- function(chunks, newline) .Call(wrap__collapse_chunks, chunks, newline)


# nolint end
