# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_b64_wrappers", use_symbols = TRUE, package_name = "b64")

#' @docType package
#' @usage NULL
#' @useDynLib b64, .registration = TRUE
NULL

encode_ <- function(what, engine) .Call(wrap__encode_, what, engine)

encode_file_ <- function(path, engine) .Call(wrap__encode_file_, path, engine)

encode_vectorized_ <- function(what, engine) .Call(wrap__encode_vectorized_, what, engine)

decode_ <- function(input, engine) .Call(wrap__decode_, input, engine)

decode_file_ <- function(path, engine) .Call(wrap__decode_file_, path, engine)

decode_vectorized_ <- function(what, engine) .Call(wrap__decode_vectorized_, what, engine)

alphabet_ <- function(which) .Call(wrap__alphabet_, which)

new_alphabet_ <- function(chars) .Call(wrap__new_alphabet_, chars)

get_alphabet_ <- function(alphabet) .Call(wrap__get_alphabet_, alphabet)

new_engine_ <- function(alphabet, config) .Call(wrap__new_engine_, alphabet, config)

engine_ <- function(which) .Call(wrap__engine_, which)

print_engine_ <- function(engine) .Call(wrap__print_engine_, engine)

new_config_ <- function(encode_padding, decode_padding_trailing_bits, decode_padding_mode) .Call(wrap__new_config_, encode_padding, decode_padding_trailing_bits, decode_padding_mode)

print_config_ <- function(config) .Call(wrap__print_config_, config)

chunk_b64 <- function(encoded, size) .Call(wrap__chunk_b64, encoded, size)

line_wrap <- function(chunks, newline) .Call(wrap__line_wrap, chunks, newline)


# nolint end
