on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: check MSRV

jobs:
  # check at least it can build
  check-msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv
      - name: run cargo-msrv
        run: cargo msrv verify --path ./src/rust/
